// Generated by https://quicktype.io

export interface User {
  id: string;
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}

export interface LoginResponse {
  user: User;
  token: string;
}

export interface Product {
  id: string;
  createdAt: string;
  name: string;
  image: string;
  price: number;
}
